### PR TITLE
1.2.0

### PR DESCRIPTION
**Pull request by andreacastello**
This PR implements an add-on for Splunk that uses WURFL Microservice client python to enrich log data and populate Splunk a specific Splunk index

### CODE REVIEW

**Comment by kamermans** [comment]
What does `TA` in `TA-WurflMicroservice` mean @andreacastello?  We should stick to a consistent naming scheme to match the other examples (ex: `event-streams-splunk_python`, or at least `lower-case-with-dashes`).

**Comment by andreacastello** [comment]
> What does `TA` in `TA-WurflMicroservice` mean @andreacastello? We should stick to a consistent naming scheme to match the other examples (ex: `event-streams-splunk_python`, or at least `lower-case-with-dashes`).

@kamermans TA stands for "technology  add-on"; it's Splunk jargon for Splunk apps that don't have a UI.  If you try to search github using the terms TA and Splunk you'll get a good number of results. Anyway we could rename the example into `TA-wurfl-microservice` to stick with the lowercase + dash naming style.

**Comment by kamermans** [comment]
Ok, nice, thanks for explaining that!  Sure, I think `TA-wurfl-microservice` is slightly better (or maybe `splunk-TA-wurfl-microservice`).

**Comment by andreacastello** [comment]
new one will be open soon

**Pull request closed without merging**
